name = "domain-check"
main = "src/index.js"
compatibility_date = "2025-11-17"
keep_vars = true

[[kv_namespaces]]
binding = "DOMAIN_KV" 
id = "2cd626cd8d7b4f93b1cb288bcacb8861" # 替换成你实际的 KV ID

[triggers]
crons = ["0 1,13 * * *"] # 北京时间 9:00 和 21:00
