name: 自动同步上游仓库

permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 * * *" # every day
  workflow_dispatch:

jobs:
  sync_latest_from_upstream:
    name: 自动同步上游仓库
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}

    steps:
      - name: 检出本仓库
        uses: actions/checkout@v4

      - name: 同步上游仓库
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          upstream_sync_repo: yutian81/domain-check
          upstream_sync_branch: main
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }} # 无需设置
          test_mode: false

      - name: 检查同步状态
        if: failure()
        run: |
          echo "[Error] 由于上游仓库的 workflow 文件变更，导致 GitHub 自动暂停了本次自动更新，你需要手动 Sync Fork 一次"
          echo "[Error] Due to changes in the workflow file of the upstream repository, GitHub has automatically paused this automatic update. You need to manually Sync Fork once"
          exit 1
